const mock = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    age: 30,
    email: "johndoe@example.com",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    age: 25,
    email: "janesmith@example.com",
  },
  {
    id: 3,
    firstName: "Bob",
    lastName: "Johnson",
    age: 40,
    email: "bobjohnson@example.com",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Davis",
    age: 28,
    email: "emilydavis@example.com",
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Brown",
    age: 35,
    email: "michaelbrown@example.com",
  },
  {
    id: 6,
    firstName: "Emma",
    lastName: "Williams",
    age: 22,
    email: "emmawilliams@example.com",
  },
  {
    id: 7,
    firstName: "David",
    lastName: "Miller",
    age: 38,
    email: "davidmiller@example.com",
  },
  {
    id: 8,
    firstName: "Olivia",
    lastName: "Jones",
    age: 27,
    email: "oliviajones@example.com",
  },
  {
    id: 9,
    firstName: "William",
    lastName: "Garcia",
    age: 33,
    email: "williamgarcia@example.com",
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Rodriguez",
    age: 21,
    email: "sophiarodriguez@example.com",
  },
  {
    id: 11,
    firstName: "James",
    lastName: "Wilson",
    age: 42,
    email: "jameswilson@example.com",
  },
  {
    id: 12,
    firstName: "Isabella",
    lastName: "Anderson",
    age: 26,
    email: "isabellaanderson@example.com",
  },
  {
    id: 13,
    firstName: "Chris",
    lastName: "Thompson",
    age: 31,
    email: "christhompson@example.com",
  },
  {
    id: 14,
    firstName: "Ava",
    lastName: "Thomas",
    age: 24,
    email: "avathomas@example.com",
  },
  {
    id: 15,
    firstName: "Ryan",
    lastName: "Moore",
    age: 37,
    email: "ryanmoore@example.com",
  },
  {
    id: 16,
    firstName: "Ashley",
    lastName: "Jackson",
    age: 20,
    email: "ashleyjackson@example.com",
  },
  {
    id: 17,
    firstName: "Matthew",
    lastName: "Martin",
    age: 36,
    email: "matthewmartin@example.com",
  },
  {
    id: 18,
    firstName: "Madison",
    lastName: "Lee",
    age: 23,
    email: "madisonlee@example.com",
  },
  {
    id: 19,
    firstName: "Daniel",
    lastName: "Walker",
    age: 39,
    email: "danielwalker@example.com",
  },
  {
    id: 20,
    firstName: "Olivia",
    lastName: "Lopez",
    age: 29,
    email: "olivialopez@example.com",
  },
];
